version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mastervisa-db
    environment:
      MYSQL_ROOT_PASSWORD: mastervisaku.com@pass # change this on prod
      MYSQL_DATABASE: master-visa # change this on prod
      MYSQL_USER: visa_user # change this on prod
      MYSQL_PASSWORD: mastervisaku.com@pass # change this on prod
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mastervisa-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: visa_user # change this on prod
      PMA_PASSWORD: mastervisaku.com@pass # change this on prod
      PMA_PORT: 3306 # change this on prod
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mastervisa-backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://visa_user:mastervisaku.com@pass@db:3306/master-visa"
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend/public:/app/public
    command: >
      sh -c "
        echo 'ğŸš€ Starting backend...';
        npx prisma migrate deploy || npx prisma db push;
        npx prisma db seed --if-present || echo 'âš ï¸ Skipping seed (maybe already seeded)';
        npm start
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mastervisa-frontend
    ports:
      - "3000:3000"
    restart: always
